### ISSUE TITLE
Application close button

### ISSUE THREAD

**Issue by zleap** [zleap/notepad#13]
Pressing the application close button (x) seems to cause the following
Traceback (most recent call last):
  File "notepad18beta.py", line 276, in <module>
    notetext = Text(window, height=290, width=150)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2911, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2058, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: can't invoke "text" command: application has been destroyed

------------------
(program exited with code: 1)
Press return to continue

I am not sure how to solve this, i am guessing i need to capture the user pressing the x in the corner of the window.   Any pointers welcome.

**Comment by zleap** [comment]
Ok i have sort of found a fix for this
http://stackoverflow.com/questions/3295270/overriding-tkinter-x-button-control-the-button-that-close-the-window


def doSomething():
    # check if saving
    # if not:
    root.destroy()

I replaced references to root with window and also replaced
root.destroy() with sys.exit()

this seems to work
